[package]
name = "yr2024"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
mimalloc = { version = "0.1.43", default-features=false }
nohash-hasher = "0.2.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
